[package]
name = "flecs_ecs"
version = "0.0.2"
edition = "2021"
authors = ["Indra de Backere <debackere.indra@gmail.com>"]
description = "Rust API for the C flecs ECS library <https://github.com/SanderMertens/flecs>"
license = ""
keywords = ["ecs", "flecs", "entity", "component", "system"]
categories = ["game-development", "api-bindings"]

[dependencies]
#debug-here = "0.2.2" #temp for development
flecs_ecs_derive = { path = "../flecs_ecs_derive" }
libc = "0.2.148"
seq-macro = "0.3.5" #temp for testing / development
rand = "0.8.5"  #temp for testing / development
#cargo-show-asm = "0.2.21"  #temp for testing / development

[dev-dependencies]
criterion = "0.5.1"
seq-macro = "0.3.5"
rand = "0.8.5" 

[[bench]]
name = "query"
harness = false

[build-dependencies]
bindgen = "0.69.4"
cc = "1.0.83"
regex = "1.9.5"

# ---> Bindgen <--- with bindgen macos generates u32 for the underlying enum of some bindings, 
#which is a bug. It should be generating i32. If you generate from macos, you'll need to revert the
# u32 to i32 in the generated bindings for the enums. More info on the issue here:
#https://github.com/rust-lang/rust-bindgen/issues/1966

[features]
flecs_generate_bindings = [] 
flecs_system = []
flecs_rules = []
flecs_timer = []
flecs_doc = []
flecs_rest = []
flecs_meta = []
flecs_metrics = []
flecs_ecs_asserts = []
flecs_enable_all_asserts = ["flecs_ecs_asserts"]
default = [
    "flecs_enable_all_asserts",
    "flecs_system",
    "flecs_timer",
    "flecs_doc",
    "flecs_rest",
    "flecs_meta",
    "flecs_metrics",
    "flecs_rules",
    #"flecs_generate_bindings"
]

[target.'cfg(any())'.dependencies]
flecs_ecs_derive = { version = "=0.1.0", path = "../flecs_ecs_derive" }