[package]
name = "flecs_ecs_bridge"
version = "0.0.2"
edition = "2021"
authors = ["Indra de Backere <debackere.indra@gmail.com>"]
description = "Rust API for the C flecs ECS library <https://github.com/SanderMertens/flecs>"
license = "MIT"
keywords = ["ecs", "flecs", "entity", "component", "system"]
categories = ["game-development", "api-bindings"]


[dependencies]
lazy_static = "1.4.0"
log = "0.4.20"
rand = "0.8"

[build-dependencies]
bindgen = "0.68.1"
cc = "1.0.83"
regex = "1.9.5"

[features]
generate_bindings = []
ecs_asserts = []
enable_all_asserts = ["ecs_asserts"]
default = ["enable_all_asserts", "generate_bindings"]
