[package]
name = "flecs_ecs_bridge"
version = "0.0.1"
edition = "2021"
authors = ["Indra de Backere <debackere.indra@gmail.com>"]
description = "Rust API for the C flecs ECS library <https://github.com/SanderMertens/flecs>"
license = "MIT"
keywords = [
    "ecs",
    "flecs",
    "c-binding",
    "entity component system",
    "game development",
    "simulation",
]
categories = ["game-development", "api-bindings"]


[dependencies]
